/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2021-06-15 17:50:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>Dashboard - SB Admin</title>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        $( document ).ready(function() {\r\n");
      out.write("        \t  $( \".tradingview-widget-container iframe\" ).clone().appendTo( \".tradingview-widget-container\" );\r\n");
      out.write("        \t});\r\n");
      out.write("        </script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("       .content {\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("}\r\n");
      out.write(".content p {\r\n");
      out.write("  font-family: sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/******/\r\n");
      out.write("\r\n");
      out.write(".ticker-container {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ticker-canvas {\r\n");
      out.write("  width: calc((200px * 15) + 2px);\r\n");
      out.write("  /* \r\n");
      out.write("  200px = minimum width of ticker item before widget script starts removing ticker codes\r\n");
      out.write("  15 = number of ticker codes\r\n");
      out.write("  2px = accounts for 1px external border\r\n");
      out.write("  */\r\n");
      out.write("  -webkit-animation-iteration-count: infinite;\r\n");
      out.write("  animation-iteration-count: infinite;\r\n");
      out.write("  -webkit-animation-timing-function: linear;\r\n");
      out.write("  animation-timing-function: linear;\r\n");
      out.write("  -webkit-animation-name: ticker-canvas;\r\n");
      out.write("  animation-name: ticker-canvas;\r\n");
      out.write("  -webkit-animation-duration: 20s;\r\n");
      out.write("  animation-duration: 20s;\r\n");
      out.write("}\r\n");
      out.write(".ticker-canvas:hover {\r\n");
      out.write("  animation-play-state: paused\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes ticker-canvas {\r\n");
      out.write("  0% {\r\n");
      out.write("    -webkit-transform: translate3d(0, 0, 0);\r\n");
      out.write("    transform: translate3d(0, 0, 0);\r\n");
      out.write("    visibility: visible;\r\n");
      out.write("  }\r\n");
      out.write("  100% {\r\n");
      out.write("    -webkit-transform: translate3d(-100%, 0, 0);\r\n");
      out.write("    transform: translate3d(-100%, 0, 0);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes ticker-canvas {\r\n");
      out.write("  0% {\r\n");
      out.write("    -webkit-transform: translate3d(0, 0, 0);\r\n");
      out.write("    transform: translate3d(0, 0, 0);\r\n");
      out.write("    visibility: visible;\r\n");
      out.write("  }\r\n");
      out.write("  100% {\r\n");
      out.write("    -webkit-transform: translate3d(-100%, 0, 0);\r\n");
      out.write("    transform: translate3d(-100%, 0, 0);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".tradingview-widget-container {\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".tradingview-widget-container iframe {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("}\r\n");
      out.write(".tradingview-widget-container iframe:nth-of-type(2) {\r\n");
      out.write("  left: 100%;\r\n");
      out.write("}\r\n");
      out.write("       </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"sb-nav-fixed\">\r\n");
      out.write("        <nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-dark\">\r\n");
      out.write("            <!-- Navbar Brand-->\r\n");
      out.write("            <a class=\"navbar-brand ps-3\" href=\"/index.do\">SDB STOCK</a>\r\n");
      out.write("            <!-- Sidebar Toggle-->\r\n");
      out.write("            <button class=\"btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0\" id=\"sidebarToggle\" href=\"#!\"><i class=\"fas fa-bars\"></i></button>\r\n");
      out.write("            <!-- Navbar Search-->\r\n");
      out.write("            <form class=\"d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" placeholder=\"Search for...\" aria-label=\"Search for...\" aria-describedby=\"btnNavbarSearch\" />\r\n");
      out.write("                    <button class=\"btn btn-primary\" id=\"btnNavbarSearch\" type=\"button\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- Navbar-->\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fas fa-user fa-fw\"></i></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"/user/LoginForm.do\">로그인</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"/user/UserRegForm.do\">회원가입</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"/user/Logout.do\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div id=\"layoutSidenav\">\r\n");
      out.write("            <div id=\"layoutSidenav_nav\">\r\n");
      out.write("                <nav class=\"sb-sidenav accordion sb-sidenav-dark\" id=\"sidenavAccordion\">\r\n");
      out.write("                    <div class=\"sb-sidenav-menu\">\r\n");
      out.write("                        <div class=\"nav\">\r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading\">Core</div>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"/index.do\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-tachometer-alt\"></i></div>\r\n");
      out.write("                                home\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading\">Interface</div>\r\n");
      out.write("                            <a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\" aria-controls=\"collapseLayouts\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-columns\"></i></div>\r\n");
      out.write("                                                                                                              주식\r\n");
      out.write("                                <div class=\"sb-sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"collapse\" id=\"collapseLayouts\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("                                <nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/stockindex.do\">주식정보 받기</a>\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/stockpredict.do\">주가예측</a>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\" aria-controls=\"collapseLayouts\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-columns\"></i></div>\r\n");
      out.write("                               BTC/ETH\r\n");
      out.write("                                <div class=\"sb-sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"collapse\" id=\"collapseLayouts\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("                                <nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/ethchart.do\">가상화폐정보 받기</a>\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/btcpredict.do\">가상화폐예측</a>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading\">ETC</div>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"/trickster.do\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-chart-area\"></i></div>\r\n");
      out.write("                               전문가판별\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"/notice/noticeList.do\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-table\"></i></div>\r\n");
      out.write("                                커뮤니티\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sb-sidenav-footer\">\r\n");
      out.write("                        <div class=\"small\">Logged in as:</div>\r\n");
      out.write("                        Start Bootstrap\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"layoutSidenav_content\">\r\n");
      out.write("                <main>\r\n");
      out.write("                <!-- TradingView Widget BEGIN -->\r\n");
      out.write("<div class=\"ticker-container\">\r\n");
      out.write("<div class=\"ticker-canvas\">\r\n");
      out.write("<div class=\"tradingview-widget-container\">\r\n");
      out.write("  <div class=\"tradingview-widget-container__widget\"></div>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://s3.tradingview.com/external-embedding/embed-widget-tickers.js\">\r\n");
      out.write("  {\r\n");
      out.write("  \"symbols\": [\r\n");
      out.write("    {\r\n");
      out.write("      \"title\": \"S&P 500\",\r\n");
      out.write("      \"proName\": \"INDEX:SPX\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"title\": \"Nasdaq 100\",\r\n");
      out.write("      \"proName\": \"INDEX:IUXX\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"title\": \"EUR/USD\",\r\n");
      out.write("      \"proName\": \"FX_IDC:EURUSD\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"title\": \"BTC/USD\",\r\n");
      out.write("      \"proName\": \"BITFINEX:BTCUSD\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"title\": \"ETH/USD\",\r\n");
      out.write("      \"proName\": \"BITFINEX:ETHUSD\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"description\": \"Apple\",\r\n");
      out.write("      \"proName\": \"NASDAQ:AAPL\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"description\": \"Berkshire\",\r\n");
      out.write("      \"proName\": \"NYSE:BRK.A\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"description\": \"Microsoft\",\r\n");
      out.write("      \"proName\": \"NASDAQ:MSFT\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"description\": \"Google\",\r\n");
      out.write("      \"proName\": \"NASDAQ:GOOG\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"description\": \"Tesla\",\r\n");
      out.write("      \"proName\": \"NASDAQ:TSLA\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"description\": \"Amazon\",\r\n");
      out.write("      \"proName\": \"NASDAQ:AMZN\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"description\": \"AUD/USD\",\r\n");
      out.write("      \"proName\": \"OANDA:AUDUSD\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"description\": \"Sony\",\r\n");
      out.write("      \"proName\": \"NYSE:SNE\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"description\": \"BHP\",\r\n");
      out.write("      \"proName\": \"BHP\"\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      \"description\": \"Telstra\",\r\n");
      out.write("      \"proName\": \"TLS\"\r\n");
      out.write("    }\r\n");
      out.write("  ],\r\n");
      out.write("  \"locale\": \"en\"\r\n");
      out.write("}\r\n");
      out.write("  </script>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- TradingView Widget END -->\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("                    <div class=\"container-fluid px-4\">\r\n");
      out.write("                       \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-xl-24\">\r\n");
      out.write("                                <div class=\"card mb-4\">\r\n");
      out.write("                                   \r\n");
      out.write("                                    <div class=\"card-body\" style=\"height: 500px;width: 100%;background-image:url('/img/index.png');background-size : cover;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </main>\r\n");
      out.write("                <footer class=\"py-4 bg-light mt-auto\">\r\n");
      out.write("                    <div class=\"container-fluid px-4\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-between small\">\r\n");
      out.write("                            <div class=\"text-muted\">Copyright &copy; Your Website 2021</div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <a href=\"#\">Privacy Policy</a>\r\n");
      out.write("                                &middot;\r\n");
      out.write("                                <a href=\"#\">Terms &amp; Conditions</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </footer>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"assets/demo/chart-area-demo.js\"></script>\r\n");
      out.write("        <script src=\"assets/demo/chart-bar-demo.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"js/datatables-simple-demo.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
