/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2021-06-16 00:00:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.btc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class btc_005fpredict_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Dashboard - SB Admin</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.1/css/all.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\"crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/chart.js@3.3.2/dist/chart.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js@2.8.0\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("\t$ ('.canvas').hide();\r\n");
      out.write("\t$ ('.finaltext').hide();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//비트코인그래프그리는로직\r\n");
      out.write("function btcsearch(){\r\n");
      out.write("\t$.ajax({                                   \r\n");
      out.write("\t\turl: \"http://127.0.0.1:9001/\",\r\n");
      out.write("\t\ttype: \"GET\",\r\n");
      out.write("\t\tdataType: \"JSON\",\r\n");
      out.write("\t\tcontentType: \"application/json; charset=UTF-8\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\tvar ds=data.map(function(e){\r\n");
      out.write("\t\t\t\treturn e.ds;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar yhat=data.map(function(e){\r\n");
      out.write("\t\t\t\treturn e.yhat;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar Close=data.map(function(e){\r\n");
      out.write("\t\t\t\treturn e.Close;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("//\t\t\t텍스트붙니느곳\r\n");
      out.write("\t\t\tvar predictprice=yhat[yhat.length -3]; //오늘자데이터\r\n");
      out.write("\t\t\tdocument.getElementById(\"text\").innerHTML = Math.floor(predictprice)+\"원\";\r\n");
      out.write("\t\t\tvar predictprice=yhat[yhat.length -2]; //오늘자데이터\r\n");
      out.write("\t\t\tdocument.getElementById(\"text2\").innerHTML = Math.floor(predictprice)+\"원\";\r\n");
      out.write("\t\t\tvar predictprice=yhat[yhat.length -1]; //오늘자데이터\r\n");
      out.write("\t\t\tdocument.getElementById(\"text3\").innerHTML = Math.floor(predictprice)+\"원\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar ctx = document.getElementById('canvas').getContext('2d');\r\n");
      out.write("\t\t\tvar myChart = new Chart(ctx, {\r\n");
      out.write("\t\t\t    type: 'line',\r\n");
      out.write("\t\t\t    data: {\r\n");
      out.write("\t\t\t        labels: ds,\r\n");
      out.write("\t\t\t        datasets: [{\r\n");
      out.write("\t\t\t            label: '#지난 종가',\r\n");
      out.write("\t\t\t            data: Close,\r\n");
      out.write("\t\t\t            backgroundColor: 'rgba(208, 221, 243,0.4)',\r\n");
      out.write("\t\t\t            borderColor: 'rgba(208, 221, 243)',\r\n");
      out.write("\t\t\t            borderWidth: 2\r\n");
      out.write("\t\t\t        },{\r\n");
      out.write("\t\t\t            label: '# 예측가',\r\n");
      out.write("\t\t\t            data: yhat,\r\n");
      out.write("\t\t\t            backgroundColor: 'rgba(108, 128, 172,0.6)',\r\n");
      out.write("\t\t\t            borderColor:'rgba(108, 128, 172)' ,\r\n");
      out.write("\t\t\t            borderWidth: 3\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        ]\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    options: {\r\n");
      out.write("\t\t\t        scales: {\r\n");
      out.write("\t\t\t        \t\r\n");
      out.write("\t\t\t            y: {\r\n");
      out.write("\t\t\t                beginAtZero: true\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$ ('.canvas').show();\r\n");
      out.write("\t\t\t$ ('.finaltext').show();\r\n");
      out.write("\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t  icon: 'success',\r\n");
      out.write("\t\t\t\t  title: '예측가 받기 성공!',\r\n");
      out.write("\t\t\t\t  text: 'slack을 확인해보세요',\r\n");
      out.write("\t\t\t\t  footer: '<a href=\"\"></a>'\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//이더리움그래프그리는로직\r\n");
      out.write("function ethsearch(){\r\n");
      out.write("\t$.ajax({                                   \r\n");
      out.write("\t\turl: \"http://127.0.0.1:9002/\",\r\n");
      out.write("\t\ttype: \"GET\",\r\n");
      out.write("\t\tdataType: \"JSON\",\r\n");
      out.write("\t\tcontentType: \"application/json; charset=UTF-8\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\tvar ds=data.map(function(e){\r\n");
      out.write("\t\t\t\treturn e.ds;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar yhat=data.map(function(e){\r\n");
      out.write("\t\t\t\treturn e.yhat;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar Close=data.map(function(e){\r\n");
      out.write("\t\t\t\treturn e.Close;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//텍스트붙니느곳\r\n");
      out.write("\t\t\tvar predictprice=yhat[yhat.length -3]; //오늘자데이터\r\n");
      out.write("\t\t\tdocument.getElementById(\"text\").innerHTML = Math.floor(predictprice)+\"원\";\r\n");
      out.write("\t\t\tvar predictprice=yhat[yhat.length -2]; //오늘자데이터\r\n");
      out.write("\t\t\tdocument.getElementById(\"text2\").innerHTML = Math.floor(predictprice)+\"원\";\r\n");
      out.write("\t\t\tvar predictprice=yhat[yhat.length -1]; //오늘자데이터\r\n");
      out.write("\t\t\tdocument.getElementById(\"text3\").innerHTML = Math.floor(predictprice)+\"원\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar ctx = document.getElementById('canvas').getContext('2d');\r\n");
      out.write("\t\t\tvar myChart = new Chart(ctx, {\r\n");
      out.write("\t\t\t    type: 'line',\r\n");
      out.write("\t\t\t    data: {\r\n");
      out.write("\t\t\t        labels: ds,\r\n");
      out.write("\t\t\t        datasets: [{\r\n");
      out.write("\t\t\t            label: '#지난 종가',\r\n");
      out.write("\t\t\t            data: Close,\r\n");
      out.write("\t\t\t            backgroundColor: 'rgba(208, 221, 243,0.4)',\r\n");
      out.write("\t\t\t            borderColor: 'rgba(208, 221, 243)',\r\n");
      out.write("\t\t\t            borderWidth: 2\r\n");
      out.write("\t\t\t        },{\r\n");
      out.write("\t\t\t            label: '# 예측가',\r\n");
      out.write("\t\t\t            data: yhat,\r\n");
      out.write("\t\t\t            backgroundColor: 'rgba(108, 128, 172,0.6)',\r\n");
      out.write("\t\t\t            borderColor:'rgba(108, 128, 172)' ,\r\n");
      out.write("\t\t\t            borderWidth: 3\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        ]\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    options: {\r\n");
      out.write("\t\t\t        scales: {\r\n");
      out.write("\t\t\t        \t\r\n");
      out.write("\t\t\t            y: {\r\n");
      out.write("\t\t\t                beginAtZero: true\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$ ('.canvas').show();\r\n");
      out.write("\t\t\t$ ('.finaltext').show();\r\n");
      out.write("\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t  icon: 'success',\r\n");
      out.write("\t\t\t\t  title: '예측가 받기 성공!',\r\n");
      out.write("\t\t\t\t  text: 'slack을 확인해보세요',\r\n");
      out.write("\t\t\t\t  footer: '<a href=\"\"></a>'\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("wrapper {\r\n");
      out.write("    margin: 0px auto;\r\n");
      out.write("    \r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col {\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  width: 22%;\r\n");
      out.write("  margin: 1%;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("  border: 1px solid #eee;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#h1 {\r\n");
      out.write("  font-size: 40px;\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  display:block;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  width: 90px;\r\n");
      out.write("  height:90px;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  margin:0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("  margin:10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bitcoin h1 {\r\n");
      out.write("  background: #f7931a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".litecoin h1 {\r\n");
      out.write("  background: #bebebe;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ethereum h1 {\r\n");
      out.write("  background: #454a75;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ripple h1 {\r\n");
      out.write("  background: #102b3e;\r\n");
      out.write("  font-size:26px;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("  line-height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#price, #bprice, #eprice, #rprice{\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".chan {\r\n");
      out.write("  margin: 20px 0 0 0;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  background: #eee;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#chan {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("@import url(https://fonts.googleapis.com/css?family=Open+Sans);\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("  \r\n");
      out.write("  font-family: 'Open Sans', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchTerm {\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  border: 3px solid #3a444e;\r\n");
      out.write("  border-right: none;\r\n");
      out.write("  padding: 5px;\r\n");
      out.write("  height: 70px;\r\n");
      out.write("  border-radius: 5px 0 0 5px;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  color: #3a444e;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   margin-left: 270px;\r\n");
      out.write("   font-size:x-large;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchTerm:focus{\r\n");
      out.write("  color: #3a444e;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchButton {\r\n");
      out.write("  width: 40px;\r\n");
      out.write("  height: 70px;\r\n");
      out.write("  border: 1px solid #3a444e;\r\n");
      out.write("  background: #3a444e;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  border-radius: 0 5px 5px 0;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("/*Resize the wrap to see the search bar change!*/\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"sb-nav-fixed\">\r\n");
      out.write("        <nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-dark\">\r\n");
      out.write("            <!-- Navbar Brand-->\r\n");
      out.write("            <a class=\"navbar-brand ps-3\" href=\"/index.do\">SDB STOCK</a>\r\n");
      out.write("            <!-- Sidebar Toggle-->\r\n");
      out.write("            <button class=\"btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0\" id=\"sidebarToggle\" href=\"#!\"><i class=\"fas fa-bars\"></i></button>\r\n");
      out.write("            <!-- Navbar Search-->\r\n");
      out.write("            <form class=\"d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" placeholder=\"Search for...\" aria-label=\"Search for...\" aria-describedby=\"btnNavbarSearch\" />\r\n");
      out.write("                    <button class=\"btn btn-primary\" id=\"btnNavbarSearch\" type=\"button\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- Navbar-->\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fas fa-user fa-fw\"></i></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"/user/LoginForm.do\">로그인</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"/user/UserRegForm.do\">회원가입</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"/user/Logout.do\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div id=\"layoutSidenav\">\r\n");
      out.write("            <div id=\"layoutSidenav_nav\">\r\n");
      out.write("                <nav class=\"sb-sidenav accordion sb-sidenav-dark\" id=\"sidenavAccordion\">\r\n");
      out.write("                    <div class=\"sb-sidenav-menu\">\r\n");
      out.write("                        <div class=\"nav\">\r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading\">Core</div>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"/index.do\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-tachometer-alt\"></i></div>\r\n");
      out.write("                                home\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading\">Interface</div>\r\n");
      out.write("                            <a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\" aria-controls=\"collapseLayouts\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-columns\"></i></div>\r\n");
      out.write("                                                                                                              주식\r\n");
      out.write("                                <div class=\"sb-sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"collapse\" id=\"collapseLayouts\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("                                <nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/stockindex.do\">주식정보 받기</a>\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/stockpredict.do\">주가예측</a>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\" aria-controls=\"collapseLayouts\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-columns\"></i></div>\r\n");
      out.write("                               BTC/ETH\r\n");
      out.write("                                <div class=\"sb-sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"collapse\" id=\"collapseLayouts\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("                                <nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/ethchart.do\">가상화폐정보 받기</a>\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/btcpredict.do\">가상화폐예측</a>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading\">ETC</div>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"/trickster.do\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-chart-area\"></i></div>\r\n");
      out.write("                               전문가판별\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"/notice/noticeList.do\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-table\"></i></div>\r\n");
      out.write("                                커뮤니티\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sb-sidenav-footer\">\r\n");
      out.write("                        <div class=\"small\">Logged in as:</div>\r\n");
      out.write("                        Start Bootstrap\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t<div id=\"layoutSidenav_content\">\r\n");
      out.write("\t\t\t<main>\r\n");
      out.write("\t\t\t<div class=\"container-fluid px-4\">\r\n");
      out.write("\t\t\t\t<h1 class=\"mt-4\">BTC/ETH</h1>\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb mb-4\">\r\n");
      out.write("\t\t\t\t\t<li class=\"breadcrumb-item active\">가상화폐예측</li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xl-24\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-chart-area me-1\"></i> 지난 6개월간의 데이터를 분석하여 3일간의  가상화폐를 예측해드립니다.\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\" id=\"div1\" style=\"height: 1000px\"><br>\r\n");
      out.write("                           \r\n");
      out.write("                         <div class=\"wrapper\">\r\n");
      out.write("                             <div class=\"col bitcoin\" onclick=\"btcsearch();\" style=\"margin-left:50px;width:40%;height:80%; transition: 0.4s ease-out;background-color: white;border-radius: 10px;cursor: pointer;\" >\r\n");
      out.write("                                    <h1 id=\"h1\">Ƀ</h1>\r\n");
      out.write("                           <h4>Bitcoin</h4>  예측하기<span id=\"bprice\"></span><div class=\"chan\">3일치  예측가<span id=\"bchange\"></span></div>\r\n");
      out.write("                             </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col ethereum\" onclick=\"ethsearch();\" style=\"margin-left:50px;width:40%;height:80%;transition: 0.4s ease-out;background-color: white;border-radius: 10px;cursor: pointer;\">\r\n");
      out.write("  <h1 id=\"h1\">Ξ</h1>\r\n");
      out.write("  <h4>Ethereum</h4>\r\n");
      out.write("  예측하기<span id=\"eprice\"></span>\r\n");
      out.write("  <div class=\"chan\">3일치  예측가<span id=\"echange\"></span></div>\r\n");
      out.write("</div>\r\n");
      out.write("                           <div class=\"canvas\" style=\"width: 100%; background-color: #f6f7fa;margin:0 auto;\">\r\n");
      out.write("                           <canvas id=\"canvas\"></canvas>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           \r\n");
      out.write("                           \r\n");
      out.write("                             <div class=\"finaltext\" style=\"background-color:#f6f7fa\"><span style=\"font-size: 20px;margin-left: 100px;\"><i class=\"fas fa-pen\"></i> 1일뒤 예측가:</span><span id=\"text\" style=\"background-color:#feffab;font-size: 30px;margin-left:20px;font-weight:bold; \"></span>\r\n");
      out.write("                               <span style=\"font-size: 20px;margin-left: 10px;\"><i class=\"fas fa-pen-alt\"></i> 2일뒤 예측가:</span>  <span id=\"text2\" style=\"background-color:#feffab;font-size: 30px;margin-left:20px;font-weight:bold;\"></span>\r\n");
      out.write("                               <span style=\"font-size: 20px;margin-left: 10px;\"><i class=\"fas fa-pen-fancy\"></i> 3일뒤 예측가:</span>  <span id=\"text3\" style=\"background-color:#feffab;font-size: 30px;margin-left:20px;font-weight:bold;\"></span></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t          </div>\r\n");
      out.write("                           \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</main>\r\n");
      out.write("\t\t\t<footer class=\"py-4 bg-light mt-auto\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid px-4\">\r\n");
      out.write("\t\t\t\t<div class=\"d-flex align-items-center justify-content-between small\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text-muted\">Copyright &copy; Your Website 2021</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">Privacy Policy</a> &middot; <a href=\"#\">Terms\r\n");
      out.write("\t\t\t\t\t\t\t&amp; Conditions</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("\t<scriptsrc=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"assets/demo/chart-area-demo.js\"></script>\r\n");
      out.write("\t<script src=\"assets/demo/chart-bar-demo.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"js/datatables-simple-demo.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
