/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2021-06-15 18:05:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.trickster;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class trickster_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Dashboard - SB Admin</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.3.1/dist/tf.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/@teachablemachine/image@0.8/dist/teachablemachine-image.min.js\"></script>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("\t$ ('.text').hide();\r\n");
      out.write("\t$ ('.text2').hide();\r\n");
      out.write("});  \r\n");
      out.write("\t// More API functions here:\r\n");
      out.write("\t// https://github.com/googlecreativelab/teachablemachine-community/tree/master/libraries/image\r\n");
      out.write("\r\n");
      out.write("\t// the link to your model provided by Teachable Machine export panel\r\n");
      out.write("\tconst URL = \"/my_model/\";\r\n");
      out.write("\r\n");
      out.write("\tlet model, webcam, labelContainer, maxPredictions;\r\n");
      out.write("\r\n");
      out.write("\t// Load the image model and setup the webcam\r\n");
      out.write("\tasync function init() {\r\n");
      out.write("\t\t  const modelURL = URL + \"model.json\";\r\n");
      out.write("\t\t   const metadataURL = URL + \"metadata.json\";\r\n");
      out.write("\r\n");
      out.write("\t\t// load the model and metadata\r\n");
      out.write("\t\t// Refer to tmImage.loadFromFiles() in the API to support files from a file picker\r\n");
      out.write("\t\t// or files from your local hard drive\r\n");
      out.write("\t\t// Note: the pose library adds \"tmImage\" object to your window (window.tmImage)\r\n");
      out.write("\t\tmodel = await\r\n");
      out.write("\t\ttmImage.load(modelURL, metadataURL);\r\n");
      out.write("\t\tmaxPredictions = model.getTotalClasses();\r\n");
      out.write("\r\n");
      out.write("\t\tlabelContainer = document.getElementById(\"label-container\");\r\n");
      out.write("\t\tfor (let i = 0; i < maxPredictions; i++) { // and class labels\r\n");
      out.write("\t\t\tlabelContainer.appendChild(document.createElement(\"div\"));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t// run the webcam image through the image model\r\n");
      out.write("\tasync function predict() {\r\n");
      out.write("\t\t// predict can take in an image, video or canvas html element\r\n");
      out.write("\t\tvar image= document.getElementById(\"face-image\")\r\n");
      out.write("\t\tconst prediction = await model.predict(image,false);\r\n");
      out.write("\t\tfor (let i = 0; i < maxPredictions; i++) {\r\n");
      out.write("\t\t\tconst classPrediction = prediction[i].className + \": \"+ prediction[i].probability.toFixed(2);\r\n");
      out.write("\t\t\tconsole.log(prediction[0].probability.toFixed(2));\r\n");
      out.write("\t\t\tconsole.log(prediction[1].probability.toFixed(2));\r\n");
      out.write("\t\t\tif(prediction[0].probability.toFixed(2)>0.60){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('.text').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(prediction[1].probability.toFixed(2)>0.80){\r\n");
      out.write("\t\t\t\t$('.text2').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction readURL(input) {\r\n");
      out.write("\t\tif (input.files && input.files[0]) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("\t\t\treader.onload = function(e) {\r\n");
      out.write("\t\t\t\t$('.image-upload-wrap').hide();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('.file-upload-image').attr('src', e.target.result);\r\n");
      out.write("\t\t\t\t$('.file-upload-content').show();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('.image-title').html(input.files[0].name);\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\treader.readAsDataURL(input.files[0]);\r\n");
      out.write("\t\t\tinit().then(function(){\r\n");
      out.write("\t\t\t\tconsole.log(\"hello\");\r\n");
      out.write("\t\t\t\tpredict();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tremoveUpload();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction removeUpload() {\r\n");
      out.write("\t\t$('.file-upload-input').replaceWith($('.file-upload-input').clone());\r\n");
      out.write("\t\t$('.file-upload-content').hide();\r\n");
      out.write("\t\t$('.image-upload-wrap').show();\r\n");
      out.write("\t\t$ ('.text').hide();\r\n");
      out.write("\t\t$ ('.text2').hide();\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t$('.image-upload-wrap').bind('dragover', function() {\r\n");
      out.write("\t\t$('.image-upload-wrap').addClass('image-dropping');\r\n");
      out.write("\t});\r\n");
      out.write("\t$('.image-upload-wrap').bind('dragleave', function() {\r\n");
      out.write("\t\t$('.image-upload-wrap').removeClass('image-dropping');\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: sans-serif;\r\n");
      out.write("\tbackground-color: #eeeeee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".file-upload {\r\n");
      out.write("    padding: 12% 3%;\r\n");
      out.write("    height:50%;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    border: solid 1.5px #f6f7fa;\r\n");
      out.write("    background-color: #f6f7fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".file-upload-btn {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground: #1FB264;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tborder-bottom: 4px solid #15824B;\r\n");
      out.write("\ttransition: all .2s ease;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".file-upload-btn:hover {\r\n");
      out.write("\tbackground: #1AA059;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\ttransition: all .2s ease;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".file-upload-btn:active {\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\ttransition: all .2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".file-upload-content {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".file-upload-input {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  width: 70%;\r\n");
      out.write("  height: 50%;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-upload-wrap {\r\n");
      out.write("    width: 60%;\r\n");
      out.write("    height:100%;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    object-fit: contain;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    border: dashed 1.5px #35465d;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-dropping, .image-upload-wrap:hover {\r\n");
      out.write("\tbackground-color: #567b9b ;\r\n");
      out.write("\tborder: 4px dashed #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-title-wrap {\r\n");
      out.write("\tpadding: 0 15px 15px 15px;\r\n");
      out.write("\tcolor: #222;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".drag-text {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".drag-text h3 {\r\n");
      out.write("\tfont-weight: 100;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tcolor: grey;\r\n");
      out.write("\tpadding: 60px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".file-upload-image {\r\n");
      out.write("\tmax-height: 500px;\r\n");
      out.write("\tmax-width: 500px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".remove-image {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground: #cd4535;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tborder-bottom: 4px solid #b02818;\r\n");
      out.write("\ttransition: all .2s ease;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".remove-image:hover {\r\n");
      out.write("\tbackground: #c13b2a;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\ttransition: all .2s ease;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".remove-image:active {\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\ttransition: all .2s ease;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"sb-nav-fixed\">\r\n");
      out.write("        <nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-dark\">\r\n");
      out.write("            <!-- Navbar Brand-->\r\n");
      out.write("            <a class=\"navbar-brand ps-3\" href=\"/index.do\">SDB STOCK</a>\r\n");
      out.write("            <!-- Sidebar Toggle-->\r\n");
      out.write("            <button class=\"btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0\" id=\"sidebarToggle\" href=\"#!\"><i class=\"fas fa-bars\"></i></button>\r\n");
      out.write("            <!-- Navbar Search-->\r\n");
      out.write("            <form class=\"d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" placeholder=\"Search for...\" aria-label=\"Search for...\" aria-describedby=\"btnNavbarSearch\" />\r\n");
      out.write("                    <button class=\"btn btn-primary\" id=\"btnNavbarSearch\" type=\"button\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- Navbar-->\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fas fa-user fa-fw\"></i></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"/user/LoginForm.do\">로그인</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"/user/UserRegForm.do\">회원가입</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"/user/Logout.do\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div id=\"layoutSidenav\">\r\n");
      out.write("            <div id=\"layoutSidenav_nav\">\r\n");
      out.write("                <nav class=\"sb-sidenav accordion sb-sidenav-dark\" id=\"sidenavAccordion\">\r\n");
      out.write("                    <div class=\"sb-sidenav-menu\">\r\n");
      out.write("                        <div class=\"nav\">\r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading\">Core</div>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"/index.do\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-tachometer-alt\"></i></div>\r\n");
      out.write("                                home\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading\">Interface</div>\r\n");
      out.write("                            <a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\" aria-controls=\"collapseLayouts\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-columns\"></i></div>\r\n");
      out.write("                                                                                                              주식\r\n");
      out.write("                                <div class=\"sb-sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"collapse\" id=\"collapseLayouts\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("                                <nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/stockindex.do\">주식정보 받기</a>\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/stockpredict.do\">주가예측</a>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\" aria-controls=\"collapseLayouts\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-columns\"></i></div>\r\n");
      out.write("                               BTC/ETH\r\n");
      out.write("                                <div class=\"sb-sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"collapse\" id=\"collapseLayouts\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("                                <nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/ethchart.do\">가상화폐정보 받기</a>\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"/btcpredict.do\">가상화폐예측</a>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading\">ETC</div>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"/trickster.do\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-chart-area\"></i></div>\r\n");
      out.write("                               전문가판별\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"/notice/noticeList.do\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-table\"></i></div>\r\n");
      out.write("                                커뮤니티\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sb-sidenav-footer\">\r\n");
      out.write("                        <div class=\"small\">Logged in as:</div>\r\n");
      out.write("                        Start Bootstrap\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t<div id=\"layoutSidenav_content\">\r\n");
      out.write("\t\t\t<main>\r\n");
      out.write("\t\t\t<div class=\"container-fluid px-4\">\r\n");
      out.write("\t\t\t\t<h2 class=\"mt-4\">전문가 판별</h2>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xl-24\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\" style=\"height: 100%; width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 style=\"text-align: center;color: grey\">사진을 업로드 하여 믿을수 있는 사람인지 확인해보세요!</h3></div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<script class=\"jsbin\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"file-upload\" style=\"height: 80%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image-upload-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"file-upload-input\" type='file'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonchange=\"readURL(this);\" accept=\"image/*\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"drag-text\" style=\"color: black\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Drag and drop a file or select add Image</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"file-upload-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"file-upload-image\" id=\"face-image\" src=\"#\" alt=\"your image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"image-title-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"label-container\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" onclick=\"removeUpload()\"\r\n");
      out.write("\t\t                                                          class=\"remove-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tRemove <span class=\"image-title\">Uploaded Image</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text\" ><h2>자산투자를 믿고 맡길수있는 <span style=\"color:#265b90;font-family: sans-serif;font-weight: 10px;font-size:70px;\">\"전문가\"</span>입니다</h2> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"text2\" ><h2>자산투자를 믿고 맡길수 없는 <span style=\"color:#265b90;font-family: sans-serif;font-weight: 10px;font-size:70px;\">\"비전문가\"</span>입니다</h2> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"webcam-container\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</main>\r\n");
      out.write("\t\t\t<footer class=\"py-4 bg-light mt-auto\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid px-4\">\r\n");
      out.write("\t\t\t\t<div class=\"d-flex align-items-center justify-content-between small\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text-muted\">Copyright &copy; Your Website 2021</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">Privacy Policy</a> &middot; <a href=\"#\">Terms\r\n");
      out.write("\t\t\t\t\t\t\t&amp; Conditions</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"assets/demo/chart-area-demo.js\"></script>\r\n");
      out.write("\t<script src=\"assets/demo/chart-bar-demo.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"js/datatables-simple-demo.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
